name: fem_analysis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - scikit-image
  - matplotlib
  - pyvista
  - vtk
  - tifffile
  - imageio
  - pip
  - pip:
      - imageio-ffmpeg
